### ISSUE TITLE
Make SSL options configurable

### ISSUE THREAD

**Issue by cah-oster** [bloonix/bloonix-plugins-wtrm#1]
TLSv1 is being hardcoded.  Please make this configurable, or at least default to "any".

https://github.com/bloonix/bloonix-plugins-wtrm/blob/02aa518f50036d8a06a3f8b214d82b2dd58938fb/plugins/check-wtrm#L139

**Comment by j-schulz** [comment]
Implemented and ready for installation.

Please update bloonix-plugin-config as well.

**Comment by cah-oster** [comment]
Sorry for the delayed response.  This fix works, thank!s! But I the "Check it!" and "Quick test" in the UI still seem to fail and not be honoring these options.  Any ideas why?
